name: AI Code Optimize

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write # perlu untuk git push
  pull-requests: write # opsi: tulis komentar manual kalau mau

jobs:
  optimize:
    runs-on: ubuntu-latest

    steps:
      # 1) Ambil kode PR
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Deteksi file yang berubah
      - id: diff
        run: |
          echo "FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..HEAD | tr '\n' ' ')" >> "$GITHUB_OUTPUT"

      # 3) Siapkan Python + OpenAI SDK
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install OpenAI SDK
        run: pip install --upgrade openai

      # 4) Panggil ChatGPT per-file & rewrite lokal
      - name: Rewrite code with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # ← ganti sesuai nama secret-mu
          FILES: ${{ steps.diff.outputs.FILES }}
        run: |
          python - <<'PY'
          import os, pathlib, textwrap, openai, json, sys

          openai.api_key = os.getenv("OPENAI_API_KEY", "")
          changed = os.getenv("FILES", "").split()
          if not changed:
              print("No files changed‽")
              sys.exit(0)

          PROMPT = textwrap.dedent("""
          Anda adalah formatter AI. 
          Tulis ulang file berikut agar:
          • Fungsi/semantik TIDAK berubah sama sekali.  
          • Gaya penulisan, penamaan, komentar, dan urutan tidak logis diperbaiki.
          • Jangan keluarkan apa pun kecuali isi file baru.
          """)

          model = "gpt-4o-mini"   # ganti jika perlu

          for path in changed:
              p = pathlib.Path(path)
              try:
                  src = p.read_text(encoding="utf-8", errors="ignore")
              except Exception as e:
                  print(f"Skip {path}: {e}")
                  continue

              prompt = PROMPT + f"\n\n```{p.suffix.lstrip('.')}\n{src}\n```"
              resp = openai.chat.completions.create(
                  model=model,
                  messages=[{"role": "system", "content": prompt}],
                  temperature=0
              )
              new_code = resp.choices[0].message.content.strip()
              if new_code and new_code != src:
                  p.write_text(new_code, encoding="utf-8")
                  print(f"Re-wrote {path}")
          PY

      # 5) Commit & push jika ada perubahan
      - name: Commit AI edits back to PR
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add ${{ steps.diff.outputs.FILES }}
            git commit -m "style(ai): auto-formatted by OpenAI"
            git push
          fi
